# Parameters for compiling

ARDUINO_DIR     = /usr/share/arduino
TARGET          = output
ARDUINO_LIBS    =  
ARDUINO_VAR_PATH  = /home/ctack/sketchbook/hardware/tiny/cores/tiny
ARDUINO_CORE_PATH = /home/ctack/sketchbook/hardware/tiny/cores/tiny

# Avrdude code for programming
BOARD_TAG               = attiny84at1
ALTERNATE_CORE          = tiny
ISP_PROG	        = avrispmkII
ISP_PORT                = usb
# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk


