# Parameters for compiling

ARDUINO_DIR     = /usr/share/arduino
TARGET          = output
ARDUINO_LIBS    =  


# Avrdude code for programming
BOARD_TAG               = attiny84
ALTERNATE_CORE          = attiny
ISP_PROG	        = avrispmkII
ISP_PORT                = usb
# Arduino makefile

include $(ARDUINO_DIR)/Arduino.mk


